import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from "next/script";
import Link from 'next/link'

import LogoImage from '../assets/img/logo.png';
import InstaImage from '../assets/img/insta.png';
import TwitterImage from '../assets/img/twitter.png'
import MenuIcon from '../assets/img/menu-icon.png'
import CloseIcon from '../assets/img/close-icon.png';
import LogoGif from '../assets/img/gifs/ppp-logo.gif'
// import BgVideo from '../assets/img/header-bg.mp4';
import firstImage from '../assets/img/1.png';
import secondImage from '../assets/img/2.png';
import thirdImage from '../assets/img/3.png';
import fourthImage from '../assets/img/4.png';
import fifthImage from '../assets/img/5.png';
import PawsImg from '../assets/img/gifs/paws.gif'
import artistImage from '../assets/img/artist-img.png'
import CatsImg from '../assets/img/cats-img.png';
import FooterLogo from '../assets/img/footer-logo.png'

export default function Home() {
    return (
        <div className={''}>
            {/* js files for proper functionality*/}
            <Script   strategy="beforeInteractive" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"/>
            <Script  strategy="afterInteractive" type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"/>
            <Script   strategy="afterInteractive" type="text/javascript" src="/js/jquery.arctext.js"/>
            <Script  strategy="afterInteractive" src="/js/bootstrap.bundle.min.js"/>
            <Script  strategy="afterInteractive" src="/js/custom-scripts.js"/>
            {/*<Script  strategy="beforeInteractive" src="/js/slick.min.js"/>*/}

            <Head>
                <title>Create Next App</title>
                {/*<meta name="description" content="Generated by create next app"/>*/}
                {/*<link rel="icon" href="/favicon.ico"/>*/}

                <link href="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css" rel="stylesheet"/>
                    {/*<link href="/css/bootstrap.min.css" rel="stylesheet"/>*/}
                {/*        <link href="/css/custom-styles.css" rel="stylesheet"/>*/}
            </Head>

            <div>
                <nav className="navbar navbar-expand-lg navbar-light bg-transparent px-0 py-5 main-navigation">
                    <div className="container">
                        <Link passHref className="navbar-brand" href="/">
                            <Image alt={'Logo Image'} src={LogoImage} className="img-fluid"/>
                        </Link>

                        <ul className="navbar-nav ml-auto">
                            <li className="nav-item">
                                <a className="nav-link" href="#">
                                    <Image alt={'twitter'} src={TwitterImage} className="img-fluid"/></a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="#">
                                    <Image alt={'instagram'} src={InstaImage} className="img-fluid"/></a>
                            </li>
                            <li className="nav-item custom-btn-li">
                                <a className="nav-link custom-btn" href="#">join discord!</a>
                            </li>
                            <li className="nav-item ml-5">
                                <a className="nav-link drawer-menu-opener" href="#">
                                    <Image alt={'Menu Icon'}
                                           src={MenuIcon}
                                           className="img-fluid"/></a>
                            </li>
                        </ul>

                        <div className="drawer-menu">
                            <div className="drawer-menu-closer">
                                <Image alt={'close Icon'} src={CloseIcon} className=""/>
                            </div>
                            <div className="drawer-menu-ul">
                                <ul className="list-unstyled">
                                    <li className="drawer-menu-li">
                                        <a href="#about">about</a>
                                    </li>
                                    <li className="drawer-menu-li">
                                        <a href="#roadmap">roadmap</a>
                                    </li>
                                    <li className="drawer-menu-li">
                                        <a href="#artist">the artist</a>
                                    </li>
                                    <li className="drawer-menu-li">
                                        <a href="#faq">faq</a>
                                    </li>
                                </ul>
                            </div>
                            <div className="drawer-menu-social">
                                <ul className="list-inline">
                                    <li className="list-inline-item">
                                        <a href="#">
                                            <Image alt={'twitter'} src={TwitterImage}/></a>
                                    </li>
                                    <li className="list-inline-item">
                                        <a href="#">
                                            <Image alt={'instagram'} src={InstaImage} className="img-fluid"/></a>
                                    </li>
                                </ul>
                            </div>
                            <div className="drawer-menu-disclaimer">
                                <a href="javascript:void(0)" data-toggle="modal"
                                   data-target="#exampleModal">disclaimer</a>
                            </div>
                        </div>
                    </div>
                </nav>

                <header className="homepage-header">
                    {/*// <!-- <img src="img/header-img.png" class="w-100" /> -->*/}
                    <div className="bg-video-wrap">
                        <video height="100%" width="100%" autoPlay muted loop>
                            <source src={'/img/header-bg.mp4'}/>
                        </video>
                    </div>
                    <div className="countdown-timer">
                        {/*// <!-- <img src="img/genesis-text.png" class="img-fluid" /> -->*/}
                        <h2 className="genesis-text genesis-text-1">Genesis sale</h2>
                        <h2 className="genesis-text genesis-text-2">opens in</h2>

                        <div className="timer-wrap">
                            <ul className="timer">
                                <li>
                                    <div className="timer-text">7</div>
                                    <div className="timer-placeholder">Days</div>
                                </li>
                                <li>
                                    <div className="timer-text">10</div>
                                    <div className="timer-placeholder">Hrs</div>
                                </li>
                                <li>
                                    <div className="timer-text">37</div>
                                    <div className="timer-placeholder">Mins</div>
                                </li>
                                <li>
                                    <div className="timer-text">20</div>
                                    <div className="timer-placeholder">Secs</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </header>

                <div id="about" className="about-section">
                    <div className="container">
                        <div className="row align-items-center">
                            <div className="col-12 col-sm-5">
                                {/*// <!-- <img src="img/logo-loop.gif" class="img-fluid about-logo-img" /> -->*/}
                                <Image alt={'Logo gif'} src={LogoGif} className="img-fluid about-logo-img"/>
                            </div>
                            <div className="col-12 col-sm-7">
                                <p>The Puffy Paws Pack are the most fluffy creatures in the metaverse. Although their
                                    looks
                                    might deceive you,
                                    they still are packed with a punch. These living creatures are your best friend in
                                    the
                                    metaverse, offering
                                    you plenty of companionship. Unlike normal dogs, these dogs do not age but remain
                                    young
                                    forever.</p>
                                <p>Frozen in time - the Puffy Paws Pack are here to stay after being frozen for 14,200
                                    years.
                                    They are finally
                                    set to be free & explore the urbanized areas of the society. Every Puffy Paws Pack
                                    NFT are
                                    looking for their
                                    new owners who will love and take good care of them. </p>
                                <p>They are led by 8 Top Dogs, as the name suggests they are the top of the pack guiding
                                    their
                                    fellow pups
                                    with knowledge. The Top Dogs are the most unique works of art, with every single one
                                    being
                                    a 1-of-1 piece,
                                    you can see their leadership resemblance from miles away.</p>
                                {/*// <!-- <a href="#"><img src="img/join-btn.png" class="img-fluid" /></a> -->*/}
                                <a href="#" className="custom-btn">join discord!</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="roadmap" className="roadmap-section">
                    <div className="roadmap-cats-carousel-outer">
                        <div className="slick roadmap-cats-carousel">
                            <div className="slick-slide">
                                <Image priority width={240} height={246} alt={'first'} src={firstImage} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} alt={'second image'} src={secondImage} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} alt={'third image'} src={thirdImage} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} src={fourthImage} alt={'fourth image'} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} src={fifthImage} alt={'fifth image'} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} alt={'first'} src={firstImage} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} alt={'second image'} src={secondImage} className="img-fluid"/>
                            </div>
                            <div className="slick-slide">
                                <Image priority width={240} height={246} alt={'third image'} src={thirdImage} className="img-fluid"/>
                            </div>
                        </div>
                    </div>
                    <div className="roadmap-section-bg-image">
                        <div className="roadmap-item zero-p">
                            <div className="roadmap-label-outer">
                                <span className="roadmap-percentage">0%</span>
                                <Image width={108} height={108} alt={'paws gif'} src={PawsImg} className="img-fluid"/>
                                <div className="roadmap-label">the start!</div>
                            </div>

                            <div className="roadmap-content">
                                <h4>0% the start</h4>
                                <p>We in the Puffy Paws Pack team think that community always comes first. So the
                                    mission for
                                    us is to make
                                    our first drop as big as possible. We want the freedom to develop the puffy paws
                                    pack
                                    together with our
                                    community.</p>
                                <p>We are announcing the drop date as soon as we are happy with the project, community
                                    and the
                                    development sid
                                    of the NFTs. We will listen to your wishes on what comes to Puffy Paws Pack. By
                                    doing this
                                    we believe that
                                    we can achieve the wanted outcome!</p>
                            </div>
                        </div>
                        <div className="roadmap-item twenty-five-p">
                            <div className="roadmap-label-outer">
                                <span className="roadmap-percentage">25%</span>
                                <Image width={108} height={108} alt={'paws gif'} src={PawsImg} className="img-fluid"/>
                                <div className="roadmap-label">staking</div>
                            </div>

                            <div className="roadmap-content">
                                <h4>25% staking!</h4>
                                <p>After minting we are creating a staking system for our NFT’s our staking starts
                                    shortly
                                    after the reveal.
                                    The value you have gained by staking can be exchanged for merchandise or other
                                    cryptocurrencies.</p>
                            </div>
                        </div>
                        <div className="roadmap-item fifty-p">
                            <div className="roadmap-label-outer">
                                <span className="roadmap-percentage">50%</span>
                                <Image width={108} height={108} alt={'paws gif'} src={PawsImg} className="img-fluid"/>
                                <div className="roadmap-label">exclusive club</div>
                            </div>

                            <div className="roadmap-content">
                                <h4>50% EXCLUSIVE CLUB!</h4>
                                <p>The Puffy Paws Pack is an exclusive club of 8888 unique ERC-721 tokens. Each
                                    non-fungible
                                    token represents
                                    the value of our vision. For example we’ll host webinars for holders with creators
                                    in the
                                    crypto & NFT
                                    industry. This will give you a market insight of the upcoming coins & the state of
                                    market.</p>
                            </div>
                        </div>
                        <div className="roadmap-item seventy-fifty-p">
                            <div className="roadmap-label-outer">
                                <span className="roadmap-percentage">75%</span>
                                <Image width={108} height={108} alt={'paws gif'} src={PawsImg} className="img-fluid"/>
                                <div className="roadmap-label">merchandise</div>
                            </div>
                            <div className="roadmap-content">
                                <h4>75% MERCHANDISE!</h4>
                                <p>We are coming up with some unique designs, that you can buy from our official
                                    merchandise
                                    store. The
                                    merchandise is exclusive to the token holders only.</p>
                            </div>
                        </div>
                        <div className="roadmap-item hundred-p">
                            <div className="roadmap-label-outer">
                                <span className="roadmap-percentage">100%</span>
                                <Image width={108} height={108} alt={'paws gif'} src={PawsImg} className="img-fluid"/>
                                <div className="roadmap-label">sec. sale royalties $ marketing</div>
                            </div>

                            <div className="roadmap-content">
                                <h4>100% Secondary sale royalties & marketing</h4>
                                <p>For every 2nd hand sale made, 4% of the sale price will go into the community fund
                                    which is
                                    being used to
                                    fund the staking function and different causes & events chosen by our
                                    community. </p>
                            </div>
                        </div>
                        <div className="roadmap-item hundred-ten-p">
                            <div className="roadmap-label-outer">
                                <span className="roadmap-percentage">110%</span>
                                <Image width={108} height={108} alt={'paws gif'} src={PawsImg} className="img-fluid"/>
                                <div className="roadmap-label">second drop.</div>
                            </div>

                            <div className="roadmap-content">
                                <h4>110% SECOND DROP</h4>
                                <p>Is being prepared after the successful first drop. By being a holder of a Puffy Paws
                                    Pack
                                    NFT you are
                                    eligible to a whitelist spot for the second drop. More info to be released after the
                                    first
                                    drop.</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="artist" className="artist-section">
                    <div className="container">
                        <div className="artist-heading-outer">
                            <h2 className="artist-heading artist-heading-1">the artist behind</h2>
                            <h2 className="artist-heading artist-heading-2">the project</h2>
                        </div>
                        <div className="row align-items-center">
                            <div className="col-12 col-sm-5">
                                <Image alt={'artist image'} src={artistImage} className="img-fluid artist-img"/>
                            </div>
                            <div className="col-12 col-sm-7">
                                <h4>@noteetu.eth</h4>
                                <p>
                                    @noteetu.eth has been a creative mind all his life. He started filming & animating
                                    at the
                                    age of 12. His
                                    most notable works include companies such as the Universal Music Group (UMG), gaming
                                    companies such as
                                    Electronic Arts (EA) and also for the biggest production companies in Europe. </p>
                                <p>
                                    @noteetu.eth has also done work for TV-series, press, digital art and co-designing
                                    NFT
                                    -projects.</p>
                                <p>
                                    During the time working in the industry he has always put the effort in to push his
                                    art
                                    and work forward. He
                                    has had his work featured in Games, TV Shows and Magazines.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="cats-image-section">
                    <Image  src={CatsImg} className="w-100" alt={'cats png'}/>
                </div>

                <div id="faq" className="faqs-section">
                    <div className="container">
                        <div className="faq-heading-outer">
                            <h2 className="faq-heading">f.a.q.</h2>
                        </div>
                        <div className="accordion" id="accordionExample">
                            <div className="toggler-outer">
                                <div className="toggle-heading" id="headingOne">
                                    <a href="javascript:void(0)" data-toggle="collapse" data-target="#collapseOne"
                                       aria-expanded="true"
                                       aria-controls="collapseOne">
                                        What is the puffy paws pack NFT?
                                    </a>
                                </div>
                                <div id="collapseOne" className="collapse show" aria-labelledby="headingOne"
                                     data-parent="#accordionExample">
                                    <div className="card-body">
                                        <p>Puffy paws pack is a private art collection of 8,888 unique puffy paw
                                            Characters,
                                            with each paw
                                            proof-of-ownership stored on the Ethereum network as an ERC-721
                                            -Non-Fungible
                                            Token (NFT).</p>
                                        <p>There are also 10 extremely rare paws that come with big cash prizes, if you
                                            are
                                            lucky enough to mint
                                            one of them.</p>
                                    </div>
                                </div>
                            </div>
                            <div className="toggler-outer">
                                <div className="toggle-heading" id="headingTwo">
                                    <a href="javascript:void(0)" data-toggle="collapse" data-target="#collapseTwo"
                                       aria-expanded="false"
                                       aria-controls="collapseTwo">
                                        What is the puffy paws pack NFT?
                                    </a>
                                </div>
                                <div id="collapseTwo" className="collapse" aria-labelledby="headingTwo"
                                     data-parent="#accordionExample">
                                    <div className="card-body">
                                        <p>Puffy paws pack is a private art collection of 8,888 unique puffy paw
                                            Characters,
                                            with each paw
                                            proof-of-ownership stored on the Ethereum network as an ERC-721
                                            -Non-Fungible
                                            Token (NFT).</p>
                                        <p>There are also 10 extremely rare paws that come with big cash prizes, if you
                                            are
                                            lucky enough to mint
                                            one of them.</p>
                                    </div>
                                </div>
                            </div>
                            <div className="toggler-outer">
                                <div className="toggle-heading" id="headingThree">
                                    <a href="javascript:void(0)" data-toggle="collapse" data-target="#collapseThree"
                                       aria-expanded="false"
                                       aria-controls="collapseThree">
                                        What is the puffy paws pack NFT?
                                    </a>
                                </div>
                                <div id="collapseThree" className="collapse" aria-labelledby="headingThree"
                                     data-parent="#accordionExample">
                                    <div className="card-body">
                                        <p>Puffy paws pack is a private art collection of 8,888 unique puffy paw
                                            Characters,
                                            with each paw
                                            proof-of-ownership stored on the Ethereum network as an ERC-721
                                            -Non-Fungible
                                            Token (NFT).</p>
                                        <p>There are also 10 extremely rare paws that come with big cash prizes, if you
                                            are
                                            lucky enough to mint
                                            one of them.</p>
                                    </div>
                                </div>
                            </div>
                            <div className="toggler-outer">
                                <div className="toggle-heading" id="headingFour">
                                    <a href="javascript:void(0)" data-toggle="collapse" data-target="#collapseFour"
                                       aria-expanded="false"
                                       aria-controls="collapseFour">
                                        What is the puffy paws pack NFT?
                                    </a>
                                </div>
                                <div id="collapseFour" className="collapse" aria-labelledby="headingFour"
                                     data-parent="#accordionExample">
                                    <div className="card-body">
                                        <p>Puffy paws pack is a private art collection of 8,888 unique puffy paw
                                            Characters,
                                            with each paw
                                            proof-of-ownership stored on the Ethereum network as an ERC-721
                                            -Non-Fungible
                                            Token (NFT).</p>
                                        <p>There are also 10 extremely rare paws that come with big cash prizes, if you
                                            are
                                            lucky enough to mint
                                            one of them.</p>
                                    </div>
                                </div>
                            </div>
                            <div className="toggler-outer">
                                <div className="toggle-heading" id="headingFive">
                                    <a href="javascript:void(0)" data-toggle="collapse" data-target="#collapseFive"
                                       aria-expanded="false"
                                       aria-controls="collapseFive">
                                        What is the puffy paws pack NFT?
                                    </a>
                                </div>
                                <div id="collapseFive" className="collapse" aria-labelledby="headingFive"
                                     data-parent="#accordionExample">
                                    <div className="card-body">
                                        <p>Puffy paws pack is a private art collection of 8,888 unique puffy paw
                                            Characters,
                                            with each paw
                                            proof-of-ownership stored on the Ethereum network as an ERC-721
                                            -Non-Fungible
                                            Token (NFT).</p>
                                        <p>There are also 10 extremely rare paws that come with big cash prizes, if you
                                            are
                                            lucky enough to mint
                                            one of them.</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="faq-btn text-center">
                            {/*// <!-- <a href="#"><img src="img/join-btn.png" class="img-fluid" /></a> -->*/}
                            <a href="#" className="custom-btn">join discord!</a>
                        </div>
                    </div>
                </div>

                <footer className="footer">
                    <div className="walking-loops-section-outer">
                        <div className="slick walking-loops-section">
                            <div className="slick-slide">
                                <video height="200" width="200" autoPlay muted loop="true">
                                    <source src="/img/walkin-loops/walking-loop_1.webm"/>
                                </video>
                                {/*<Image src={walkingDog1} class="img-fluid" />*/}
                            </div>
                            <div className="slick-slide">
                                <video height="200" width="200" autoPlay muted loop="true">
                                    <source src="/img/walkin-loops/walking-loop_2.webm"/>
                                </video>
                                {/*// <!-- <img src="img/walkin-loops/walking loop_2.gif" class="img-fluid" /> -->*/}
                            </div>
                            <div className="slick-slide">
                                <video height="200" width="200" autoPlay muted loop="true">
                                    <source src="/img/walkin-loops/walking-loop_3.webm"/>
                                </video>
                                {/*// <!-- <img src="img/walkin-loops/walking loop_3.gif" class="img-fluid" /> -->*/}
                            </div>
                        </div>
                    </div>

                    <div className="py-5">
                        <a href="#">
                            <Image alt={'footer logo'} src={FooterLogo} className="img-fluid"/>
                        </a>
                    </div>
                    <div className="footer-text mb-3">all rights reserved</div>
                    <div className="footer-text">
                        <a href="javascript:void(0)" data-toggle="modal" data-target="#exampleModal">disclaimer</a>
                    </div>
                </footer>


                {/*// <!-- Modal -->*/}
                <div className="modal fade disclaimer-modal" id="exampleModal" tabIndex="-1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <button type="button" className="close close-modal" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <div className="modal-body">
                                <h4 className="disclaimer-heading">disclaimer</h4>
                                <p>The Puffy Paws Pack NFT’s are non-fungible tokens representing ownership of a digital
                                    artwork only.
                                    Accordingly, no information on this website (or any other documents mentioned
                                    therein) is
                                    or may be
                                    considered to be advice or an invitation to enter into an agreement for any
                                    investment
                                    purpose. Further, as
                                    Puffy Paws Pack NFT’s represent artwork, nothing on this website qualifies or is
                                    intended
                                    to be an offering
                                    of securities in any jurisdiction nor does it constitute an offer or an invitation
                                    to
                                    purchase shares,
                                    securities or other financial product.</p>
                                <p>Due to the artistic nature of the project, neither this document nor the Puffy Paws
                                    Pack
                                    NFT’s have been
                                    registered with or approved by any regulator in any jurisdiction. It remains in your
                                    responsibility to
                                    assure that the purchase of the Puffy Paws Pack NFT and the associated art is in
                                    compliance with laws and
                                    regulations in your jurisdiction.</p>
                                <p>We undertake no obligation to publicly update or revise any information or opinions
                                    published on the
                                    website. We reserve the right to amend the information at any time without prior
                                    notice. <br/>Puffy Paws
                                    Pack is not a registered broker, analyst or investment advisor. If you are willing
                                    to, or
                                    have purchased
                                    Puffy Paws Pack, you agree that you are not purchasing a security or investment. The
                                    Puffy
                                    Paws Pack team
                                    can not be held liable for any losses or taxes you may incur. Do conduct your own
                                    due
                                    diligence and consult
                                    your financial advisor before making any investment decisions.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    )
}
